services:
  - type: web
    name: dentipro-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist/dental
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
